#!/bin/ash
ping=`ping -c 3 www.baidu.com|awk 'NR==7 {print $4}'`
if [ $ping -ne 0 ]
	then
	./inout &
else
	while true
	do
		ping=`ping -c 3 www.baidu.com|awk 'NR==7 {print $4}'`
		if [ $ping -ne 0 ]
		    then
			./inout &
			break
		fi
	done
fi
